#!/usr/bin/python2

from __future__ import print_function

import base64
import pickle
import sys

if len(sys.argv) > 1 and sys.argv[1] == '-u':
    for line in sys.stdin:
        try:
            print(pickle.loads(base64.b64decode(line)))
        except Exception as e:
            print(e, file=sys.stderr)

else:
    for line in sys.stdin:
        print(repr(base64.b64encode(pickle.dumps(line))))
