#!python3
import sentry_sdk
import time
import sys
import json
from sentry_sdk.envelope import Envelope
sentry_sdk.init(auto_enabling_integrations=False, default_integrations=False)

CHECKPOINT_SIZE = 10000

i = 0

checkpoint = time.time()

for file in sys.argv[1:]:
    with open(file, "rb") as f:
        envelope = Envelope.deserialize(f.read())

    sentry_sdk.Hub.current.client.transport._send_envelope(envelope)

    if i % CHECKPOINT_SIZE == 0:
        next_checkpoint = time.time()
        print("taking {}s per envelope".format((next_checkpoint - checkpoint) / CHECKPOINT_SIZE))

        checkpoint = next_checkpoint

    i += 1
